spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security
    username: security
    password: security
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000

  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  main:
    allow-bean-definition-overriding: true